-- Run this in Supabase Dashboard → SQL Editor
-- https://supabase.com/dashboard/project/_/sql

create table if not exists public.movies (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  year integer not null,
  rating text not null,
  imdb numeric(2, 1) not null,
  duration text not null,
  genre text[] not null default '{}',
  thumbnail text not null,
  backdrop text not null,
  video_url text not null,
  is_trending boolean not null default false,
  is_featured boolean not null default false,
  is_new boolean not null default false,
  cast_members text[] not null default '{}',
  director text not null,
  language text not null default 'English',
  created_at timestamptz not null default now()
);

alter table public.movies enable row level security;

create policy "Movies are publicly readable"
  on public.movies
  for select
  using (true);

-- Optional: allow authenticated users to manage their watchlist later
-- create table public.watchlist (...);
