-- CineStream: run this ONCE in Supabase SQL Editor
-- https://supabase.com/dashboard/project/euqluysfqrakddmyfcqz/sql/new

create table if not exists public.movies (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  year integer not null,
  rating text not null,
  imdb numeric(2, 1) not null,
  duration text not null,
  genre text[] not null default '{}',
  thumbnail text not null,
  backdrop text not null,
  video_url text not null,
  is_trending boolean not null default false,
  is_featured boolean not null default false,
  is_new boolean not null default false,
  cast_members text[] not null default '{}',
  director text not null,
  language text not null default 'English',
  created_at timestamptz not null default now()
);

alter table public.movies enable row level security;

drop policy if exists "Movies are publicly readable" on public.movies;
create policy "Movies are publicly readable"
  on public.movies for select using (true);

insert into public.movies (
  title, description, year, rating, imdb, duration, genre,
  thumbnail, backdrop, video_url, is_trending, is_featured, is_new,
  cast_members, director, language
) values
(
  'Interstellar',
  'A team of explorers travel through a wormhole in space in an attempt to ensure humanity''s survival.',
  2014, 'PG-13', 8.6, '2h 49m', array['Sci-Fi','Drama','Adventure'],
  'https://picsum.photos/seed/interstellar/300/450',
  'https://picsum.photos/seed/interstellar/1400/600',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
  true, true, false,
  array['Matthew McConaughey','Anne Hathaway','Jessica Chastain'],
  'Christopher Nolan', 'English'
),
(
  'The Dark Knight',
  'Batman must accept one of the greatest tests of his ability to fight injustice when the Joker wreaks havoc on Gotham.',
  2008, 'PG-13', 9.0, '2h 32m', array['Action','Crime','Drama'],
  'https://picsum.photos/seed/darkknight/300/450',
  'https://picsum.photos/seed/darkknight/1400/600',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
  true, false, false,
  array['Christian Bale','Heath Ledger','Aaron Eckhart'],
  'Christopher Nolan', 'English'
),
(
  'Inception',
  'A thief who steals corporate secrets through dream-sharing technology is given the task of planting an idea.',
  2010, 'PG-13', 8.8, '2h 28m', array['Action','Sci-Fi','Thriller'],
  'https://picsum.photos/seed/inception/300/450',
  'https://picsum.photos/seed/inception/1400/600',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
  true, false, true,
  array['Leonardo DiCaprio','Joseph Gordon-Levitt','Ellen Page'],
  'Christopher Nolan', 'English'
),
(
  'Dune: Part Two',
  'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.',
  2024, 'PG-13', 8.5, '2h 46m', array['Sci-Fi','Adventure'],
  'https://picsum.photos/seed/dune2/300/450',
  'https://picsum.photos/seed/dune2/1400/600',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
  true, false, true,
  array['Timothée Chalamet','Zendaya','Rebecca Ferguson'],
  'Denis Villeneuve', 'English'
),
(
  'Oppenheimer',
  'The story of J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II.',
  2023, 'R', 8.9, '3h 0m', array['Biography','Drama','History'],
  'https://picsum.photos/seed/oppenheimer/300/450',
  'https://picsum.photos/seed/oppenheimer/1400/600',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
  true, false, false,
  array['Cillian Murphy','Emily Blunt','Matt Damon'],
  'Christopher Nolan', 'English'
),
(
  'Top Gun: Maverick',
  'After more than thirty years of service, Pete Mitchell pushes the envelope as a courageous test pilot.',
  2022, 'PG-13', 8.2, '2h 11m', array['Action','Drama'],
  'https://picsum.photos/seed/topgun/300/450',
  'https://picsum.photos/seed/topgun/1400/600',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
  true, false, false,
  array['Tom Cruise','Miles Teller','Jennifer Connelly'],
  'Joseph Kosinski', 'English'
),
(
  'Avengers: Endgame',
  'The Avengers assemble once more to reverse the actions of Thanos and restore balance to the universe.',
  2019, 'PG-13', 8.4, '3h 1m', array['Action','Adventure','Sci-Fi'],
  'https://picsum.photos/seed/endgame/300/450',
  'https://picsum.photos/seed/endgame/1400/600',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4',
  true, false, false,
  array['Robert Downey Jr.','Chris Evans','Mark Ruffalo'],
  'Anthony Russo, Joe Russo', 'English'
),
(
  'Parasite',
  'Greed and class discrimination threaten the symbiotic relationship between the wealthy Park family and the Kim clan.',
  2019, 'R', 8.5, '2h 12m', array['Drama','Thriller'],
  'https://picsum.photos/seed/parasite/300/450',
  'https://picsum.photos/seed/parasite/1400/600',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
  false, false, false,
  array['Song Kang-ho','Lee Sun-kyun','Cho Yeo-jeong'],
  'Bong Joon-ho', 'Korean'
);
